class ResponseGenerator {
    constructor() {
        this.responses = {
            sadness: [
                "I hear how much pain you're in, and I want you to know that your feelings are completely valid and important. It's okay to feel this way, and there's no timeline for healing. You're stronger than you realize, and reaching out like this shows incredible courage. Remember that this difficult moment doesn't define your entire story. You have the resilience within you to get through this, and it's okay to take things one day at a time. Your worth isn't determined by your sadness, and brighter days are ahead.",
                "It sounds like you're going through a really tough time, and I want you to know that you're not alone in this journey. Your pain matters, and acknowledging it is the first step toward feeling better. You deserve compassion and kindness, especially from yourself. Life can be overwhelming sometimes, but you have the strength to face these challenges. Please be patient with yourself as you navigate through this. Things won't feel this heavy forever, and there's hope waiting for you on the other side.",
                "Your feelings are completely valid, and I appreciate you being honest about what you're experiencing. Sadness is a natural human emotion, and it doesn't mean something is wrong with you. Take the time you need to process these emotions without judgment. You're worthy of love and support, and it's wonderful that you're giving yourself permission to feel. Remember that reaching out for support is a sign of strength, not weakness. You have so much value, and this chapter of sadness will eventually transform into growth and wisdom.",
                "I'm truly honored that you trusted me with what you're feeling. Your vulnerability is a beautiful thing, and it takes real courage to open up about your pain. Know that your emotions are heard, understood, and respected. You deserve to feel supported and cared for during this difficult time. The weight you're carrying right now is real, but you don't have to carry it alone. Every small step forward is progress, and I'm here to support you through this journey toward healing and hope."
            ],
            stress: [
                "That sounds incredibly overwhelming, and I want you to know that your stress is completely understandable given everything you're dealing with. When life feels like too much, it's important to remember that you don't have to handle it all at once. Take a moment to breathe deeply and remind yourself that you're doing the best you can. Breaking your challenges into smaller, manageable pieces can make them feel less daunting. You have more capability and resilience than you might realize right now. Remember to be gentle with yourself and celebrate the small victories. Taking care of yourself isn't selfish—it's necessary.",
                "It's clear you're carrying a lot right now, and I want to affirm that you're doing an amazing job managing everything on your plate. The stress you're feeling is valid, and it shows how much you care about getting things right. However, remember that you're not meant to do everything perfectly. Be kind to yourself during this hectic time and remember that rest and self-care are productive too. You have the strength and wisdom to navigate through this challenging period. Take things one step at a time, and know that this overwhelming season won't last forever.",
                "Take a step back if you can and remind yourself that you're capable of handling more than you think. Breaking things down into smaller, more manageable tasks might help lift some of that weight from your shoulders. Your stress is telling you something important: that you need to prioritize your well-being. You're valuable, and your mental health matters just as much as your accomplishments. Remember to celebrate your efforts, not just your outcomes. You're doing better than you think, and taking it one moment at a time is perfectly okay.",
                "Your stress is completely understandable, and I want to affirm that you're handling an incredibly challenging situation with grace. Consider taking a break when possible, even if it's just for a few minutes, to reset and recharge. You deserve rest, and giving yourself permission to slow down is an act of strength. Remember that you're not responsible for controlling everything, and that's okay. Focus on what you can control and let go of what you can't. You're more resilient than you believe, and this stressful period will pass."
            ],
            anger: [
                "I can deeply sense your frustration, and I want you to know that your feelings are completely justified. When we encounter unfair situations or feel unheard, anger is a natural and healthy response. Your anger is valid, and it's okay to feel it fully. Rather than pushing it away, allow yourself to acknowledge it and process it in healthy ways. You have every right to feel upset about what's happened, and your emotions matter. Channel this energy into positive action if you can, knowing that your passion and conviction can create real change. You're not wrong for feeling angry.",
                "It's absolutely okay to be angry, and I want to affirm that your feelings are completely legitimate. You have the right to feel upset when your boundaries are crossed or when you face injustice. Your anger is a signal that something important matters to you, and that shows how much you care. Don't let anyone make you feel bad for having these emotions. Instead, honor them and use them as fuel for positive change in your life. You're strong for allowing yourself to feel, and your anger is a powerful part of who you are.",
                "It sounds like something really unfair has happened, and your anger is a completely reasonable response to that injustice. You have every right to feel upset, and taking time to process these intense emotions is important. Your feelings are valid, and expressing them is healthy. Remember that anger doesn't make you a bad person—it makes you human. Allow yourself to feel what you need to feel, and then decide how you want to move forward. You have the wisdom and strength to navigate through this, and your anger can become a catalyst for positive change.",
                "Your anger makes complete sense given the situation you're facing, and I want to affirm that your feelings are valid and important. Let it out if it helps—whether through talking, writing, exercise, or creative expression. Don't suppress these emotions, because they're telling you something valuable about what matters to you. You have the right to stand up for yourself and your beliefs. Your passion and intensity are strengths, not flaws. Remember that this anger is temporary, and while you feel it, use it to fuel positive action and growth."
            ],
            happiness: [
                "That's absolutely wonderful, and I'm genuinely so glad you're feeling good right now! Your happiness is contagious, and it brings me joy to see you thriving. This positive moment in your life is something to celebrate and hold onto. You've earned this happiness through your efforts and resilience, and you deserve to bask in this good feeling. Share this joy with those around you, as your positivity can lift others up too. Remember this feeling during harder times, knowing that you're capable of experiencing this happiness again. Keep nurturing the things that bring you joy and fulfillment.",
                "It sounds like things are genuinely going well for you, and I couldn't be happier for you! This is a moment worth celebrating and savoring fully. You've worked hard to get to this place, and you should be incredibly proud of yourself. Your success and happiness are a reflection of your effort, determination, and character. Don't let this moment pass by without truly appreciating it. The positive energy you're experiencing right now is something special, so hold onto it and let it fuel your future endeavors. You deserve all the goodness that's coming your way.",
                "Your joy is absolutely contagious, and I love hearing about the amazing things happening in your life! Keep up that incredible positive energy because it's making a real difference in your world. You're doing something right, and that's worth celebrating. Your happiness comes from genuine effort and positive choices, and you should be proud of who you are and what you're achieving. Continue to nurture the things and people that bring you joy, because that's where real fulfillment comes from. You're an inspiration, and your happiness matters.",
                "That's absolutely fantastic, and I love hearing about the wonderful things happening in your life! Your joy is a beautiful thing to witness, and it shows that you're living in alignment with what matters to you. You've earned this happiness, and you deserve to enjoy every moment of it. Your positive energy is powerful and can inspire others around you. Remember to be grateful for these good moments while they're happening, and use them as motivation to keep moving forward. You're thriving, and that's truly wonderful to see."
            ],
            neutral: [
                "Thank you so much for sharing your thoughts with me. I really appreciate your openness and willingness to communicate. Your perspective is valuable, and I want you to know that your voice matters. I'm genuinely interested in understanding what you're experiencing and what matters to you. Please know that I'm here to listen without judgment and support you in whatever way I can. Your feelings and thoughts are important, and sharing them takes courage. I'm honored to be part of your journey.",
                "I really appreciate you opening up to me. That takes courage, and I want you to know that your willingness to share shows strength. Your experiences and perspectives are valuable, and I'm genuinely interested in hearing more about what's on your mind. What else is weighing on your heart? I'm here to listen and support you through whatever you're facing. Your well-being matters, and I'm committed to understanding your needs. Thank you for letting me be part of your story.",
                "Thank you for the update, and I appreciate you keeping me in the loop about what's happening in your life. I care about how you're doing and what you're experiencing. It sounds like you're navigating some interesting situations, and I want to support you through them. How are you really doing with all of this? I'm genuinely interested in your well-being and your thoughts. Please feel free to share as much or as little as you'd like. I'm here for you.",
                "I'm truly listening, and I want you to know that your words matter to me. Please, tell me more about what you're experiencing. Your story is important, and I'm honored that you're sharing it with me. I'm genuinely interested in understanding your perspective and what's happening in your world. Your thoughts, feelings, and experiences are valuable, and I want to support you fully. Don't hesitate to express yourself fully. I'm here for all of it."
            ]
        };
    }

    generateResponse(tone) {
        const responseList = this.responses[tone] || this.responses.neutral;
        const randomIndex = Math.floor(Math.random() * responseList.length);
        return responseList[randomIndex];
    }

    getResponseOptions(tone) {
        return this.responses[tone] || this.responses.neutral;
    }
}

module.exports = ResponseGenerator;
